language: node_js
node_js:
- 8.12.0
sudo: false
cache:
  yarn: true
script:
- yarn test
before_deploy:
  - git config --local user.name "olegkleiman"
  - git config --local user.email "oleg_kleyman@hotmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "dist/build.js"
  draft: false
  overwrite: true
  on:
    tags: true
