language: node_js

node_js:
- '8.12.0'

sudo: false

cache:
  yarn: true

script:
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 2b7ee6f0dd0b73e1467840e63fa2d3cc7da71265
  keep-history: true
  on:
    branch: master
