language: node_js

node_js:
- '8.12.0'

sudo: false

cache:
  yarn: true

script:
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 93e41041f2a2803387c1fcbd43bf1dbf9381e5cf
  keep-history: true
  on:
    branch: master
