language: node_js
node_js:
- 8.12.0
sudo: false
cache:
  yarn: true
script:
- yarn test
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "./dist/bundle/js"
  on:
    repo: Tel-Aviv/mob_closed_streets
