language: node_js
node_js:
- 8.12.0
sudo: false
cache:
  yarn: true
script:
- yarn test
deploy:
  provider: releases
  skip_cleanup: true
  api_key: 348ce37bb30e0b9b0b502577030e1e216fecd7fe
  file_glob: true
  file: dist/build.js
  on:
    tags: false
