language: node_js
node_js:
- 8.12.0
sudo: false
cache:
  yarn: true
script:
- yarn test
deploy:
  provider: releases
  api_key: 6d87a11319c63305b48b47eec944b1d8970e28df
  file: "./dist/bundle.js"
  on:
    repo: Tel-Aviv/mob_closed_streets
