language: node_js
node_js:
- 8.12.0
sudo: false
cache:
  yarn: true
script:
- yarn test
deploy:
  provider: releases
  api_key: e0a4a9ab5e2867c060b435cf716f10e49fe56366
  file: "./dist/bundle/js"
  on:
    repo: Tel-Aviv/mob_closed_streets
